config/routes.rb
ReSrcR::Application.routes.draw do

  resources :resources

  resources :jobs
  
  resources :subjobs
  
  resources :constraints do
    collection do
      get 'get_first_subjobs'
      get 'get_second_subjobs'
    end
  end
  
  resources :system, :path => 'settings'

  root :to => 'application#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/job.rb
class Job < ActiveRecord::Base
  # Relations
  has_many :subjobs
  
  # Validations
  validates_presence_of :name
  
  # Attributes
  attr_accessible :name
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.find(:all)
  end
  
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(params[:job])
 
    respond_to do |format|
      if @job.save
        format.html  { redirect_to(:jobs,
                      :notice => 'Job was successfully created.') }
      else
        format.html  { render :action => "new" }
      end
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.haml
%h4 Jobs

%table.responsible
  %thead
    %tr
      %td ID
      %td Name
      %td Earliest starting time
      %td Latest ending time
      %td # of subjobs
  - @jobs.each do |@job|
    %tbody
      %tr
        %td= @job.id 
        %td= @job.name
        %td= @job.earliest_starting_time || "None"
        %td= @job.latest_ending_time || "None"
        %td= @job.subjobs.count || 0
        

%h6 Actions
%p
  = link_to new_job_path do
    = image_tag("icons/buttons/add.png", :class => "icon")
    Add new

app/views/jobs/new.haml
%h4 Add new Job

- if @job.errors.any?
  %errorExplanation
    %h5.error= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
    %ul
      - @job.errors.full_messages.each do |msg|
        %li.suberror= msg

= form_for @job, :url => { :action => "create" } do |f|
  %p#name
    %label Name:
    = f.text_field :name
    
  %p
    = f.submit "Create job"

%h6 Actions
%p
  = link_to jobs_path do
    = image_tag("icons/buttons/back.png", :class => "icon")
    Back