config/routes.rb
ReSrcR::Application.routes.draw do

  resources :resources

  resources :jobs
  
  resources :subjobs
  
  resources :constraints do
    collection do
      get 'get_first_subjobs'
      get 'get_second_subjobs'
    end
  end
  
  resources :system, :path => 'settings'

  root :to => 'application#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/subjob.rb
class Subjob < ActiveRecord::Base
  # Relations
  belongs_to :job
  has_and_belongs_to_many :resources
  has_many :constraints_as_subjob_one, :class_name => 'Constraint', :foreign_key => 'subjob_one_id'
  has_many :constraints_as_subjob_two, :class_name => 'Constraint', :foreign_key => 'subjob_two_id'
  has_many :timetables

  # Validations
  validates_presence_of :name
  validates_presence_of :job_id
  validates_presence_of :number_of_steps
  validates_uniqueness_of :name, :scope => [:job_id]

  # Attributes
  attr_accessible :name
  attr_accessible :number_of_steps
  attr_accessible :job_id
  attr_accessible :resource_ids
  
  def is_start_subjob?
    # Is there any constraint where the type is start and this subjob is subjob one?
    @constraint_type_start = ConstraintType.where(:name => "Start").first
    @constraint = Constraint.where(:constraint_type_id => @constraint_type_start.id, :subjob_one_id => self.id).all
    
    unless @constraint.blank?
      return true
    else
      return false
    end
  end
  
  def is_end_subjob?
    # Is there any constraint where the type is end and this subjob is subjob two?
    @constraint_type_end = ConstraintType.where(:name => "End").first
    @constraint = Constraint.where(:constraint_type_id => @constraint_type_end.id, :subjob_two_id => self.id).all
    
    unless @constraint.blank?
      return true
    else
      return false
    end
  end
end

app/controllers/subjobs_controller.rb
class SubjobsController < ApplicationController
  before_filter :load_common_resources
  
  def index
    @subjobs = Subjob.find(:all)
  end
  
  def new
    @subjob = Subjob.new    
  end
  
  def create
    params[:subjob][:resource_ids] ||= []
    @subjob = Subjob.new(params[:subjob])
 
    respond_to do |format|
      if @subjob.save
        format.html  { redirect_to(:subjobs,
                      :notice => 'Subjob was successfully created.') }
      else
        format.html  { render :action => "new" }
      end
    end
  end
  
  def show
    # Load subjob details
    @subjob = Subjob.find(params[:id])
  end
  
  private
  def load_common_resources
    # Get jobs
    @jobs = Job.find(:all, :order => :id)
    
    # Get resources
    @resources = Resource.find(:all, :order => :id)
  end
  
end

app/helpers/subjobs_helper.rb
module SubjobsHelper
  def get_all_subjobs_by_constraint(constraint_type)
    @constraint_type_start = ConstraintType.find_by_name("Start")
    @constraint_type_end = ConstraintType.find_by_name("End")
    
    if constraint_type == @constraint_type_start
      @subjobs = Subjob.find(:all, :joins => "JOIN 'constraints' ON constraints.subjob_two_id = subjobs.id",   :conditions => ["constraints.constraint_type_id = ?", constraint_type.id], :order => "subjobs.number_of_steps")
    elsif constraint_type == @constraint_type_end
      @subjobs = Subjob.find(:all, :joins => "JOIN 'constraints' ON constraints.subjob_one_id = subjobs.id",   :conditions => ["constraints.constraint_type_id = ?", constraint_type.id], :order => "subjobs.number_of_steps")
    end
  end 
  
  def get_all_subjobs_by_constraint_by_name(name)
    @constraint_type = ConstraintType.find_by_name(name)
    get_all_subjobs_by_constraint(@constraint_type)
  end
  
  def get_all_subjobs_by_constraint_type_start
    get_all_subjobs_by_constraint_by_name("Start")
  end
  
  def get_all_subjobs_by_constraint_type_end
    get_all_subjobs_by_constraint_by_name("End")
  end
  
  def get_start_subjobs
    @constraint_type = ConstraintType.find_by_name("Start")
    @start_subjobs = Subjob.find(:all, :joins => "JOIN 'constraints' ON constraints.subjob_one_id = subjobs.id",   :conditions => ["constraints.constraint_type_id = ?", @constraint_type.id], :order => "subjobs.number_of_steps").uniq
    return @start_subjobs
  end
  
  def get_end_subjobs
    @constraint_type = ConstraintType.find_by_name("End")
    @end_subjobs = Subjob.find(:all, :joins => "JOIN 'constraints' ON constraints.subjob_two_id = subjobs.id",   :conditions => ["constraints.constraint_type_id = ?", @constraint_type.id], :order => "subjobs.number_of_steps").uniq
    return @end_subjobs
  end
  
  def get_all_predecessors(subjob, subjobs, only_same_job = true)
    if subjob.blank? or subjob.is_start_subjob?
      return
    end    
    
    # Get constraints where current subjob is subjob_two and where the subjobs are in the same job
    if only_same_job
      @constraints_inverted = Constraint.find(:all, :include => { :subjob_two => :job }, :conditions => { "jobs.id" => subjob.job.id, "subjob_two_id" => subjob.id })
    else
      @constraints_inverted = Constraint.find(:all, :include => { :subjob_two => :job }, :conditions => { "subjob_two_id" => subjob.id })
    end
    @constraints_inverted.each do |constraint_inverted|
      # Add subjob, if its not the start subjob
      if not constraint_inverted.subjob_one.is_start_subjob?
        subjobs.push(constraint_inverted.subjob_one)
        # Get predecessors of subjob, recursion \o/
        get_all_predecessors(constraint_inverted.subjob_one, subjobs)
      else
        return
      end
    end
  end
  
  def get_all_successors(subjob, subjobs, only_same_job = true)   
    if subjob.blank? or subjob.is_end_subjob?
      return
    end    
    
    # Get constraints where current the subjob is subjob_one
    if only_same_job
      # The subjobs have to be in the same job
      @constraints = Constraint.find(:all, :include => { :subjob_one => :job }, :conditions => { "jobs.id" => subjob.job.id, "subjob_one_id" => subjob.id })
    else
      @constraints = Constraint.find(:all, :include => { :subjob_one => :job }, :conditions => { "subjob_one_id" => subjob.id })
    end
    @constraints.each do |constraint|
      # Add subjob, if its not the end subjob
      if not constraint.subjob_two.is_end_subjob?
        subjobs.push(constraint.subjob_two)
        # Get successors of subjob, recursion \o/
        get_all_successors(constraint.subjob_two, subjobs)
      else
        return
      end
    end
  end
  
  def get_next_successors(subjob, subjobs, only_same_job = true, include_end_subjob = false)
    if subjob.blank? or subjob.is_end_subjob?
      return
    end    
    
    # Get constraints where the current subjob is subjob_one
    @constraints = subjob.constraints_as_subjob_one
    @constraints.each do |constraint|
      if only_same_job
        if constraint.subjob_one.job_id == subjob.job_id and constraint.subjob_two.job_id == subjob.job_id
          if include_end_subjob
            subjobs.push(constraint.subjob_two)
          else
            unless constraint.subjob_one.is_end_subjob?
              subjobs.push(constraint.subjob_two)
            end
          end
        end
      else
        if include_end_subjob
          subjobs.push(constraint.subjob_two)
        else
          unless constraint.subjob_one.is_end_subjob?
            subjobs.push(constraint.subjob_two)
          end
        end
      end
    end
  end
  
  def get_next_predecessors(subjob, subjobs, only_same_job = true, include_start_subjob = false)
    if subjob.blank? or subjob.is_start_subjob?
      return
    end    
    
    # Get constraints where current the subjob is subjob_two
    @constraints = subjob.constraints_as_subjob_two
    @constraints.each do |constraint|
      if only_same_job
        if constraint.subjob_one.job_id == subjob.job_id and constraint.subjob_two.job_id == subjob.job_id
          if include_start_subjob
            subjobs.push(constraint.subjob_one)
          else
            unless constraint.subjob_one.is_start_subjob?
              subjobs.push(constraint.subjob_one)
            end
          end
        end
      else
        if include_start_subjob
          subjobs.push(constraint.subjob_one)
        else
          unless constraint.subjob_one.is_start_subjob?
            subjobs.push(constraint.subjob_one)
          end
        end
      end
    end
  end  
end

app/views/subjobs/index.haml
%h4 Subjobs

%table.responsible
  %thead
    %tr
      %td ID
      %td Name
      %td Job
      %td Number of steps
      %td Number of resources
      %td Actions
  - @subjobs.each do |@subjob|
    %tbody
      %tr
        %td= @subjob.id 
        %td= @subjob.name
        %td
          - if @subjob.job
            = @subjob.job.name
          - else
            No job
        %td= @subjob.number_of_steps
        %td= @subjob.resources.size
        %td
          = link_to subjob_path(@subjob) do
            = image_tag("icons/buttons/show.png", :class => "icon")
          = link_to subjob_path(@subjob), :method => :delete do 
            = image_tag("icons/buttons/delete.png", :class => "icon")
            
%h6 Actions
%p
  = link_to new_subjob_path do
    = image_tag("icons/buttons/add.png", :class => "icon")
    Add new

app/views/subjobs/new.haml
%h4 Add new subjob

- if @subjob.errors.any?
  %errorExplanation
    %h5= "#{pluralize(@subjob.errors.count, "error")} prohibited this subjob from being saved:"
    %ul
      - @subjob.errors.full_messages.each do |msg|
        %li= msg

= form_for @subjob, :url => { :action => "create" } do |f|
  %p
    %label Number of steps
    = f.select :number_of_steps, options_for_select((Resrcr.minimum_number_of_steps..Resrcr.maximum_number_of_steps).step(1).to_a.map{|s| ["#{s}", s]})
  
  %p.bold#name
    %label Name
    = f.text_field :name
  
  %p.bold#job
    = f.label :job
    = f.collection_select(:job_id, @jobs, :id, :name, { :include_blank => true }, {})
  
  %p.bold#resources
    = f.label :resources
    - for resource in @resources do
      %p
        = check_box_tag 'subjob[resource_ids][]', resource.id, @subjob.resources.include?(resource)
        = resource.name
    
  %p
    = f.submit "Create subjob"

%h6 Actions
%p
  = link_to subjobs_path do
    = image_tag("icons/buttons/back.png", :class => "icon")
    Back

app/views/subjobs/show.haml
%h4
  Subjob details:
  = @subjob.name 

%table.responsible
  %tbody
    %tr
      %td.bold ID
      %td= @subjob.id
    %tr
      %td.bold Name
      %td= @subjob.name     
    %tr
      %td.bold Number of steps
      %td= @subjob.number_of_steps

%h5 Resources
- unless @subjob.resources.blank?
  %table.responsible
    %thead
      %tr
        %td ID
        %td Name
        %td Capacity
        %td Steps per time unit
        
    %tbody
    - @subjob.resources.each do |@resource|
      %tr
        %td= @resource.id
        %td= @resource.name
        %td= @resource.capacity
        %td= @resource.steps_per_time_unit
        
- else
  Subjob has no resources.
  
%h6 Actions
%p
  = link_to subjobs_path do
    = image_tag("icons/buttons/back.png", :class => "icon")
    Back